/**
 * ByteRover CLI generated rule template tag.
 */
export const BRV_RULE_TAG = 'Generated by ByteRover CLI for'

/**
 * Boundary markers for managed ByteRover rule sections.
 * Used to identify and replace ByteRover-generated content in shared instruction files.
 */
export const BRV_RULE_MARKERS = {
  END: '<!-- END BYTEROVER RULES -->',
  START: '<!-- BEGIN BYTEROVER RULES -->',
} as const

const sliceBrvSection = (content: string): string | undefined => {
  const startIdx = content.indexOf(BRV_RULE_MARKERS.START)
  const endIdx = content.indexOf(BRV_RULE_MARKERS.END)
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return undefined
  return content.slice(startIdx, endIdx)
}

/**
 * Checks if the BRV markers section contains MCP tool references (brv-query/brv-curate).
 * Only checks within the markers section to avoid false positives from user content.
 */
export const hasMcpToolsInBrvSection = (content: string): boolean => {
  const brvSection = sliceBrvSection(content)
  if (brvSection === undefined) return false
  return brvSection.includes('brv-query') || brvSection.includes('brv-curate')
}

/**
 * Extracts the agent name from a `Generated by ByteRover CLI for X` footer
 * inside the BRV markers section. Used to disambiguate which agent owns a
 * shared rule file (Amp / Codex / OpenCode all map to AGENTS.md).
 *
 * Returns undefined when markers are missing, when the footer is absent
 * (legacy pre-footer installs), or when the footer line is empty.
 */
export const extractInstalledAgentFromBrvSection = (content: string): string | undefined => {
  const brvSection = sliceBrvSection(content)
  if (brvSection === undefined) return undefined

  const tagWithDelimiter = `${BRV_RULE_TAG} `
  const tagIdx = brvSection.indexOf(tagWithDelimiter)
  if (tagIdx === -1) return undefined

  const afterTag = brvSection.slice(tagIdx + tagWithDelimiter.length)
  const newlineIdx = afterTag.indexOf('\n')
  const agentLine = newlineIdx === -1 ? afterTag : afterTag.slice(0, newlineIdx)
  const agent = agentLine.trim()
  return agent.length === 0 ? undefined : agent
}
